export const GEAR = [
  {
    id: 0,
    name: "Lightning 45",
    brand: "Exped",
    weight: 39.9,
    gearType: "Backpack",
    category: "Essentials",
  },
  {
    id: 1,
    name: "AirContact 60 + 10",
    brand: "Dueter",
    weight: 84.6,
    gearType: "Backpack",
    category: "Essentials",
  },
  {
    id: 2,
    name: "Parsec 0F/-18C",
    brand: "Therma-rest",
    weight: 34,
    gearType: "Sleeping Bag",
    category: "Essentials",
  },
  {
    id: 3,
    name: "Aspect 2",
    brand: "Mountain Hardware",
    weight: 46.7,
    gearType: "Tent",
    category: "Essentials",
  },
  {
    id: 4,
    name: "NeoAir XTherm NXT",
    brand: "Therma-rest",
    weight: 16,
    gearType: "Sleeping Pad",
    category: "Essentials",
  },
  {
    id: 5,
    name: "Jetboil Zip",
    brand: "Jetboil",
    weight: 12,
    gearType: "Cooking System",
    category: "Kitchen",
  },
  {
    id: 6,
    name: "Jetboil Jetpower Fuel",
    brand: "Jetboil",
    weight: 7,
    gearType: "Cooking System",
    category: "Kitchen",
  },
];
